version: '3'
services:
    web:
        image: ehab123/tradebyte:latest
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
        env_file:
            - .env_prod
    redis:
        image: redis
