version: '3'
services:
    web:
        image: ehab123/tradebyte:latest
        deploy:
          replicas: 2
          restart_policy:
            condition: on-failure
 
        
        ports:
            - "8000:8000"
        volumes:
            - .:/code
        depends_on:
            - redis
        env_file:
            - .env
    redis:
        image: redis
        deploy:
          replicas: 2
          restart_policy:
            condition: on-failure

