version: '3'
services:
    web:
        image: ehab123/tradebyte
        ports:
            - "8000:8000"
        volumes:
            - .:/code
        depends_on:
            - redis
        env_file:
            - .env
    redis:
        image: redis
